project_id = "ffhizsrrsqolhjasovyd"

[functions.generate-documents]
verify_jwt = false

[functions.parse-resume-pdf]
verify_jwt = false

[functions.openai-webhook]
verify_jwt = false

[functions.coverletter-webhook]
verify_jwt = false
